apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-participant-portal-service
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}-participant-portal
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
      port: {{ .port }}
    {{ end }}
