apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dataplane-config
data:
  EDC_HOSTNAME: {{ .Values.configMap.hostname | quote }}
  WEB_HTTP_CONTROL_PATH: "/api/control"
  
  EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: {{ .Values.configMap.transferProxyTokenVerifierPublicKeyAlias | quote }}
  EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: {{ .Values.configMap.transferProxyTokenSignerPrivateKeyAlias | quote }}
  EDC_DPF_SELECTOR_URL: {{ .Values.configMap.dpfSelectorUrl | quote }}
  WEB_HTTP_PUBLIC_PATH: "/api/public"
  EDC_PARTICIPANT_ID: {{ .Values.configMap.participantId | quote}}
  EDC_VAULT_HASHICORP_URL: {{ .Values.global.vault.url | quote }}
  # EDC_VAULT_HASHICORP_TOKEN: {{ .Values.global.vault.token | quote }}
  EDC_DATASOURCE_DEFAULT_URL: {{ .Values.global.postgres.db.url | quote}}
  EDC_DATASOURCE_DEFAULT_USER: {{ .Values.global.postgres.db.user | quote}}
  EDC_DATASOURCE_DEFAULT_PASSWORD: {{ .Values.global.postgres.db.password | quote}}
  EDC_SQL_SCHEMA_AUTOCREATE: "true"
  EDC_IAM_DID_WEB_USE_HTTPS: "true"
  EDC_IAM_STS_OAUTH_TOKEN_URL: {{ .Values.configMap.iamStsOauthTokenUrl | quote }}
  EDC_IAM_STS_OAUTH_CLIENT_ID: {{ .Values.configMap.iamStsOauthClientId | quote }}
  EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS: {{ .Values.configMap.iamStsOauthClientSecretAlias | quote }}
  EDC_WEB_REST_CORS_ENABLED: "true"
  EDC_WEB_REST_CORS_HEADERS: "origin,content-type,accept,authorization,x-api-key"
  EDC_WEB_REST_CORS_ORIGIN: "*"
  EDC_WEB_REST_CORS_METHODS: "GET, POST, DELETE, PUT, OPTIONS"
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1044"
  USE_WAIT_FOR_IT: "false"
  EDC_DATAPLANE_API_PUBLIC_BASEURL: {{ .Values.configMap.edcDataplaneApiPublicBaseurl | quote }}
  EDC_CONTROL_ENDPOINT: {{ .Values.configMap.edcControlEndpoint | quote }}