# kubectl create configmap keycloak-realm-config --from-file=realm.json=realms/realm.json -n {{ .Release.Namespace }} --dry-run=client -o yaml | kubectl apply -f - && kubectl apply -f job-import-realm.yaml -n {{ .Release.Namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-import-api
spec:
  template:
    spec:
      containers:
        - name: realm-importer
          image: alpine:latest
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak-service:8080"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin-password"

          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache curl jq sed
              
              echo "Waiting for Keycloak to be ready..."
              until curl -s -f "$KEYCLOAK_URL/health/ready" > /dev/null; do
                echo "Keycloak is unavailable - waiting..."
                sleep 5
              done
              
              echo "Getting Admin Token..."
              TOKEN=$(curl -s -X POST "$KEYCLOAK_URL/realms/master/protocol/openid-connect/token" \
                -H "Content-Type: application/x-www-form-urlencoded" \
                -d "username=$KEYCLOAK_USER" \
                -d "password=$KEYCLOAK_PASSWORD" \
                -d "grant_type=password" \
                -d "client_id=admin-cli" | jq -r '.access_token')
              
              if [ "$TOKEN" == "null" ]; then
                echo "Error obtaining token. Check credentials."
                exit 1
              fi
              
              echo "Sending Realm to the API..."
              HTTP_CODE=$(curl -s -o /dev/stderr -w "%{http_code}" -X POST "$KEYCLOAK_URL/admin/realms" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                -d @/config/realm.json)
              
              if [ "$HTTP_CODE" -eq 201 ]; then
                echo "✅ Realm 'dataspace' created successfully!"
              elif [ "$HTTP_CODE" -eq 409 ]; then
                echo "⚠️ Realm 'dataspace' already exists. Nothing done."
              else
                echo "❌ Import failed. HTTP Code: $HTTP_CODE"
                exit 1
              fi

          volumeMounts:
            - name: realm-config-vol
              mountPath: /config
              readOnly: true

      restartPolicy: OnFailure
      volumes:
        - name: realm-config-vol
          configMap:
            name: keycloak-realm-config