apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: {{ .Release.Name }}-vault
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port | default 8200 }}
      targetPort: {{ .Values.service.targetPort | default 8200 }}
      protocol: TCP
      name: {{ .Values.service.portName | default "http" }}
  selector:
    app: {{ .Release.Name }}-vault
