apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-participant-portal-config
data:
  NODE_ENV: {{ .Values.configMap.nodeEnv | quote }}
  VITE_KEYCLOAK_URL: {{ .Values.configMap.viteKeycloakUrl | quote }}
  VITE_KEYCLOAK_REALM: {{ .Values.configMap.viteKeycloakRealm | quote }}
  VITE_KEYCLOAK_CLIENT_ID: {{ .Values.configMap.viteKeycloakClientId | quote }}
  VITE_KEYCLOAK_CLIENT_SECRET: {{ .Values.configMap.viteKeycloakClientSecret | quote }}

  VITE_EDC_CONNECTOR_NAME: {{ .Values.configMap.viteEdcConnectorName | quote }}
  VITE_EDC_CONNECTOR_BASE_URL: {{ .Values.configMap.viteEdcConnectorBaseUrl | quote }}
  VITE_EDC_CONNECTOR_CATALOG_URL: {{ .Values.configMap.viteEdcConnectorCatalogUrl | quote }}
  VITE_EDC_CONNECTOR_MANAGEMENT_URL: {{ .Values.configMap.viteEdcConnectorManagementUrl | quote }}
  VITE_EDC_CONNECTOR_IDENTITY_URL: {{ .Values.configMap.viteEdcConnectorIdentityUrl | quote }}
  VITE_EDC_CONNECTOR_PUBLIC_URL: {{ .Values.configMap.viteEdcConnectorPublicUrl | quote }}
  VITE_EDC_CONNECTOR_AUTH_URL: {{ .Values.configMap.viteEdcConnectorAuthUrl | quote }}
  VITE_EDC_CONNECTOR_API_KEY: {{ .Values.configMap.viteEdcConnectorApiKey | quote }}
  VITE_EDC_CONNECTOR_ID: {{ .Values.configMap.viteEdcConnectorId | quote }}

  VITE_CONNECTOR_CHECK_INTERVAL: {{ .Values.configMap.viteConnectorCheckInterval | quote }}
  VITE_CONNECTOR_TIMEOUT:  {{ .Values.configMap.viteConnectorTimeout | quote }}
  DEV: {{ .Values.configMap.dev | quote }}

  VITE_HPC_BASE_URL: {{ .Values.configMap.viteHpcBaseUrl | quote }}
  VITE_HPC_AUTH_KEY: "X-API-KEY"
  VITE_HPC_AUTH_CODE: "hpc_api_shared_secret"