apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-config
data:
  KC_PROXY: {{ .Values.configMap.keycloakProxy | quote}}
  KC_HOSTNAME_STRICT: {{ .Values.configMap.keycloakHostnameStrict | quote}}
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: {{ .Values.configMap.keycloakHostnameBackchannelDynamic | quote}}
  KC_HOSTNAME: {{ .Values.configMap.keycloakHostname | quote}}
  KC_FRONTEND_URL: {{ .Values.configMap.keycloakFrontendUrl | quote}}
  KC_HEALTH_ENABLED: {{ .Values.configMap.keycloakHealthEnable | quote}}
  KC_LOG_LEVEL: {{ .Values.configMap.keycloakLogLevel | quote}}
