apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak
    spec:
      containers:
        - name: {{ .Release.Name }}-keycloak
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          args:
            - "start-dev"
            - "--import-realm"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-keycloak-config
            - secretRef:
                name: {{ .Values.secret.name }}

          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{ end }}

          volumeMounts:
            - name: {{ .Values.deployment.volumes.name }}
              mountPath: {{ .Values.deployment.volumes.mountPath }}

      volumes:
        - name: {{ .Values.deployment.volumes.name }}
          configMap:
            name: {{ .Release.Name }}-keycloak-config-realm
