apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: {{ .Values.secret.type | quote }}
stringData:
  KEYCLOAK_ADMIN: {{ .Values.secret.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secret.keycloakAdminPassword | quote }}