global:
  postgres:
    db:
      url: jdbc:postgresql://{{PARTICIPANT}}-postgresql:5432/{{PARTICIPANT}}
      name: {{PARTICIPANT}}
      user: {{PARTICIPANT}}
      password: {{PARTICIPANT}}
  vault:
    url: http://{{PARTICIPANT}}-vault:8200
    token: root

controlplane:

  configMap:
    hostname: "{{HOST}}"
    iamIssuerId: "did:web:{{HOST}}:identityhub:did"
    managementAuthDacKeyUrl: "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/certs"
    managementAuthKey: "{{AUTH_KEY_B64}}"
    catalogAuthDacKeyUrl: "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/certs"
    catalogAuthKey: "{{AUTH_KEY_B64}}"
    participantAuthDacKeyUrl: "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/certs"
    participantAuthKey: "{{AUTH_KEY_B64}}"
    iamStsPrivateKeyAlias: "did:web:{{HOST}}:identityhub:did#key-1"
    iamStsPublicKeyId: "did:web:{{HOST}}:identityhub:did#key-1"
    participantId: "did:web:{{HOST}}:identityhub:did"
    iamStsOauthClientSecretAlias: "did:web:{{HOST}}:identityhub:did-sts-client-secret"
    iamStsOauthClientId: "did:web:{{HOST}}:identityhub:did"
    iamAuthorityId: "did:web:demostrador-datalife.srv.cesga.es:dataspace-issuer:did-publisher"
    dspCallbackAddress: "https://{{HOST}}/controlplane/dsp/api/dsp"
    iamStsOauthTokenUrl: "http://{{PARTICIPANT}}-identityhub:9292/api/sts/token"
    edcParisPublicBaseurl: "https://demostrador-datalife.srv.cesga.es/participant-information-service/participant-public/api/participant-public"
    edcControlEndpoint: "http://{{PARTICIPANT}}-controlplane:9191/api/control"
    edcUseCaseApiUrl: "https://demostrador-datalife.srv.cesga.es/participant-information-service/use-case/api/use-case"

  deployment:
    initContainers:
      dependencies:
        - name: "Postgres"
          host: "{{PARTICIPANT}}-postgresql"
          port: 5432
        - name: "Vault"
          host: "{{PARTICIPANT}}-vault"
          port: 8200
        - name: "Identityhub"
          host: "{{PARTICIPANT}}-identityhub"
          port: "8182"

  ingress:
    host: {{HOST}}
    tlsSecretName: {{TLS_SECRET_NAME}}
    annotations:x
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "{{CLUSTER_ISSUER}}"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /controlplane/management(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-controlplane
          servicePort: 8181
      - path: /controlplane/participant(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-controlplane
          servicePort: 8081
      - path: /controlplane/version(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-controlplane
          servicePort: 7171
      - path: /controlplane/dsp(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-controlplane
          servicePort: 8282
      - path: /controlplane/catalog(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-controlplane
          servicePort: 17171

dataplane:

  configMap:
    hostname: "{{HOST}}"
    transferProxyTokenVerifierPublicKeyAlias: "did:web:{{HOST}}:identityhub:did#key-1"
    transferProxyTokenSignerPrivateKeyAlias: "did:web:{{HOST}}:identityhub:did#key-1"
    dpfSelectorUrl: "http://{{PARTICIPANT}}-controlplane:9191/api/control/v1/dataplanes"
    participantId: "did:web:{{HOST}}:identityhub:did"
    iamStsOauthClientSecretAlias: "did:web:{{HOST}}:identityhub:did-sts-client-secret"
    iamStsOauthClientId: "did:web:{{HOST}}:identityhub:did"
    iamStsOauthTokenUrl: "https://{{HOST}}/identityhub/sts/api/sts/token"
    edcDataplaneApiPublicBaseurl: "https://{{HOST}}/dataplane/public/api/public"
    edcControlEndpoint: "http://{{PARTICIPANT}}-dataplane:9191/api/control"

  deployment:
    initContainers:
      dependencies:
        - name: "Postgres"
          host: "{{PARTICIPANT}}-postgresql"
          port: 5432
        - name: "Vault"
          host: "{{PARTICIPANT}}-vault"
          port: 8200
        - name: "Controlplane"
          host: "{{PARTICIPANT}}-controlplane"
          port: 9191

  ingress:
    host: {{HOST}}
    tlsSecretName: {{TLS_SECRET_NAME}}
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "{{CLUSTER_ISSUER}}"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /dataplane/public(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-dataplane
          servicePort: 8185

identityhub:
  configMap:
    hostname: "{{HOST}}"
    iamStsPrivateKeyAlias: "did:web:{{HOST}}:identityhub:did#key-1"
    iamStsPublicKeyId: "did:web:{{HOST}}:identityhub:did#key-1"
    ihIamId: "did:web:{{HOST}}:identityhub:did"
    ihApiSuperuserKey: "{{SUPER_USER_KEY_B64}}"

  deployment:
    initContainers:
      dependencies:
        - name: "Postgres"
          host: "{{PARTICIPANT}}-postgresql"
          port: 5432
        - name: "Vault"
          host: "{{PARTICIPANT}}-vault"
          port: 8200

  ingress:
    host: {{HOST}}
    tlsSecretName: {{TLS_SECRET_NAME}}
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "{{CLUSTER_ISSUER}}"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /identityhub/version(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-identityhub
          servicePort: 7171
      - path: /identityhub/credentials(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-identityhub
          servicePort: 13131
      - path: /identityhub/identity(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-identityhub
          servicePort: 15151

  ingressDid:
    host: {{HOST}}
    tlsSecretName: {{TLS_SECRET_NAME}}
    paths:
      - path: /identityhub/did(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          serviceName: {{PARTICIPANT}}-identityhub
          servicePort: 10100

oauth2-proxy:
  enable: true
  config:
    clientID: "{{PARTICIPANT}}-proxy"
    clientSecret: "{{CLIENT_SECRET}}"
    configFile: |
      http_address = "0.0.0.0:4180"
      pass_authorization_header = true
      custom_templates_dir = "/templates"
      
      whitelist_domains = [ 
        "{{HOST}}", 
        "{{HOST_KC}}"
      ]
      
      email_domains = [ "*" ]
      cookie_refresh = "5m"
      cookie_expire  = "8h"
      
      provider = "keycloak-oidc"
      oidc_issuer_url = "https://{{HOST_KC}}/realms/dataspace"
      
      login_url = "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/auth"
      redeem_url = "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/token"
      oidc_jwks_url = "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/certs"
      validate_url = "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/userinfo"
      skip_oidc_discovery = true
      
      backend_logout_url = "https://{{HOST_KC}}/realms/dataspace/protocol/openid-connect/logout?id_token_hint={id_token}"
      redirect_url = "https://{{HOST}}/oauth2/callback"
      
      allowed_groups = [ "/{{PARTICIPANT}}-group" ]
      skip_provider_button = true
      
      upstreams = [
        "http://{{PARTICIPANT}}-participant-portal-service:80/",
        "http://{{PARTICIPANT}}-controlplane:8181/api/management/",
        "http://{{PARTICIPANT}}-controlplane:17171/api/catalog/",
        "http://{{PARTICIPANT}}-controlplane:8081/api/participant/"
      ]

  extraVolumes:
    - name: templates
      configMap:
        name: {{PARTICIPANT}}-oauth2-proxy-templates
  extraVolumeMounts:
    - name: templates
      mountPath: "/templates"
      readOnly: true

  service:
    portNumber: 4180

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/pass-authorization-header: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      cert-manager.io/cluster-issuer: "{{CLUSTER_ISSUER}}"
    className: "nginx"
    path: /
    pathType: Prefix
    hosts:
      - "{{HOST}}"
    tls:
      - secretName: {{TLS_SECRET_NAME}}
        hosts:
          - "{{HOST}}"

participant-portal:
  configMap:
    nodeEnv: "production"
    viteIconUrl: "/icons/gradiant.svg"
    viteKeycloakUrl: "https://{{HOST_KC}}"
    viteKeycloakRealm: "dataspace"
    viteKeycloakAuthClientId: "edc-frontend"
    viteEdcConnectorName: "{{PARTICIPANT}}"
    viteEdcConnectorBaseUrl: "https://{{HOST}}/"
    viteEdcConnectorCatalogUrl: "/api/catalog"
    viteEdcConnectorManagementUrl: "/api/management"
    viteEdcConnectorParticipantUrl: "/api/participant"
    viteEdcConnectorIdentityUrl: "https://{{HOST}}/identityhub/identity/api/identity"
    viteEdcConnectorPublicUrl: "https://{{HOST}}/dataplane/public/api/public"
    viteEdcConnectorAuthUrl: "https://{{HOST}}/"
    viteEdcConnectorId: "did:web:{{HOST}}:identityhub:did"
    viteConnectorCheckInterval: "300000"
    viteConnectorTimeout: "15000"
    dev: "true"

seeding:
  enabled: true
  participant:
    url: "https://{{HOST}}"
    name: {{PARTICIPANT}}
    did: "did:web:{{HOST}}:identityhub:did"
    didB64: "{{DID_B64}}"
    keyId: "did:web:{{HOST}}:identityhub:did#key-1"
    privateKeyAlias: "did:web:{{HOST}}:identityhub:did#key-1"

  credentialIssuer:
    did: "did:web:demostrador-datalife.srv.cesga.es:dataspace-issuer:did-publisher"
    pid: "credential-request-{{PARTICIPANT}}-1"

  controlplane:
    service:
      observability:
        name: {{PARTICIPANT}}-controlplane
        port: 8182
      management:
        name: {{PARTICIPANT}}-controlplane
        port: 8181

  identityhub:
    service:
      observability:
        name: {{PARTICIPANT}}-identityhub
        port: 8182
      identity:
        name: {{PARTICIPANT}}-identityhub
        port: 15151

  serviceEndpoints:
    credentials:
      id: {{PARTICIPANT}}-credentialservice-1
      host: "{{HOST}}/identityhub/credentials"
      name: {{PARTICIPANT}}-identityhub
      port: 13131
      didB64: "{{DID_B64}}"
    controlplane:
      id: {{PARTICIPANT}}-dsp
      host: "{{HOST}}/controlplane/dsp"
      name: {{PARTICIPANT}}-controlplane
      port: 8282

  policies:
    - file: files/policies/general-role.json
    - file: files/policies/pharmacy-role.json
    - file: files/policies/healthauthority-role.json
    - file: files/policies/investigationcentre-role.json
    - file: files/policies/techcentre-role.json
    - file: files/policies/membership.json

  apiKeys:
    management: "{{AUTH_KEY_B64}}"
    identityhub: "{{SUPER_USER_KEY_B64}}"

  keycloakUrl: "https://{{HOST_KC}}"
  targetRealm: "dataspace"
  postLogoutRedirectUrl: "/oauth2/sign_out?rd=https%3A%2F%2F{{HOST_KC}}%2Frealms%2Fdataspace%2Fprotocol%2Fopenid-connect%2Flogout%3Fpost_logout_redirect_uri%3Dhttps%3A%2F%2F{{HOST}}%2F%26client_id%3D{{PARTICIPANT}}-proxy"
  auth:
    secretName: "keycloak-secrets"
    secretPasswordKey: "admin-password"
  client:
    clientId: "{{PARTICIPANT}}-proxy"
    publicUrl: "https://{{HOST}}"
    secret: "{{CLIENT_SECRET}}"
    did: "did:web:{{HOST}}:identityhub:did"
  defaultUser:
    create: true
    password: "1234"