namespace: <k8s-namespace>  # Ej: cesga-ds-connector-2

tls:
  useLetsEncrypt: <true|false>
  # Si useLetsEncrypt es false, definir los certificados:
  keycloak:
    secretName: <keycloak-tls-secret>
    crt: <ruta-al-certificado-tls-kc.crt>
    key: <ruta-a-la-clave-tls-kc.key>
  connector:
    secretName: <connector-tls-secret>
    crt: <ruta-al-certificado-tls.crt>
    key: <ruta-a-la-clave-tls.key>
  # Si useLetsEncrypt es true, definir el email:
  email: <email-para-lets-encrypt>
connector:
  name: <nombre-del-participante>
  logo: <URL-del-logo>
  address: <direccion-del-connector>       # Ej: <institution>-ds-connector-1.domain.es
  password: <password-del-usuario>

keycloak:
  address: <direccion-del-keycloak>        # Ej: <institution>-ds-connector-1-kc.domain.es
  adminPassword: <password-admin-kc>
