namespace: cesga-ds-connector-2
tls:
  useLetsEncrypt: false
  keycloak:
    secretName: keycloak-tls-cert
    crt: tls/tls-kc.crt
    key: tls/tls-kc.key
  connector:
    secretName: cesga-ds-connector-2-tls-cert
    crt: tls/tls.crt
    key: tls/tls.key
user:
  password: <user-password>
connector:
  name: connector
  address: <institution>-ds-connector-1.domain.es
keycloak:
  address: cesga-ds-connector-2-kc.dataspace.cesga.es
  adminPassword: <kc-admin-password>
