{{- if .Values.seeding.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-seed-identityhub"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-identityhub
          image: curlimages/curl:8.5.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for IdentityHub to be ready..."
              until curl -s --fail "http://{{ .Values.seeding.identityhub.service.observability.name }}:{{ .Values.seeding.identityhub.service.observability.port }}/api/observability/check/health"; do
                echo "IdentityHub not ready, retrying in 5s..."
                sleep 5
              done
              echo "IdentityHub is ready!"
      containers:
        - name: seed-identityhub
          image: curlimages/curl:8.5.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Registering participant in IdentityHub"
              curl -s --fail --location \
                --request POST "http://{{ .Values.seeding.identityhub.service.identity.name }}:{{ .Values.seeding.identityhub.service.identity.port }}/api/identity/v1alpha/participants" \
                --header "Content-Type: application/json" \
                --header "x-api-key: {{ .Values.seeding.apiKeys.identityhub }}" \
                --data @- <<EOF
              {
                "roles": [],
                "serviceEndpoints": [
                  {
                    "type": "CredentialService",
                    "serviceEndpoint": "https://{{ .Values.seeding.serviceEndpoints.credentials.host }}/api/credentials/v1/participants/{{ .Values.seeding.serviceEndpoints.credentials.didB64 }}",
                    "id": {{ .Values.seeding.serviceEndpoints.credentials.id | quote}}
                  },
                  {
                    "type": "ProtocolEndpoint",
                    "serviceEndpoint": "https://{{ .Values.seeding.serviceEndpoints.controlplane.host }}/api/dsp",
                    "id": {{ .Values.seeding.serviceEndpoints.controlplane.id | quote}}
                  }
                ],
                "active": true,
                "participantId": {{ .Values.seeding.participant.did | quote}},
                "did": {{ .Values.seeding.participant.did | quote}},
                "key": {
                  "keyId": {{ .Values.seeding.participant.keyId | quote}},
                  "privateKeyAlias": {{ .Values.seeding.participant.privateKeyAlias | quote}},
                  "keyGeneratorParams": {
                    "algorithm": "EC"
                  }
                }
              }
              EOF
              echo "\nSuccessfully registered participant."
{{- end }}
