apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-pvc
spec:
  accessModes:
    - {{ .Values.volume.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.volume.size | default "1Gi" }}
  storageClassName: {{ .Values.volume.storageClass }}
