apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.image.repository | default "postgres" }}:{{ .Values.image.tag | default "15" }}"
          ports:
            - containerPort: {{ .Values.service.port | default 5432 }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.global.postgres.db.name | default "postgres" }}
            - name: POSTGRES_USER
              value: {{ .Values.global.postgres.db.user | default "postgres" }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.postgres.db.password | default "postgres" }}
          volumeMounts:
            - name: {{ .Release.Name }}-postgresql-data
              mountPath: {{ .Values.volume.mountPath | default "/var/lib/postgresql/data" }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-postgresql-data
      spec:
        accessModes:
          - {{ .Values.volume.accessMode | default "ReadWriteOnce" }}
        storageClassName: {{ .Values.volume.storageClass }}
        resources:
          requests:
            storage: {{ .Values.volume.size | default "1Gi" }}