apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-identityhub
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-identityhub
  template:
    metadata:
      name: {{ .Release.Name }}-identityhub
      labels:
        app: {{ .Release.Name }}-identityhub
    spec:
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecret }}
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              {{- range .Values.deployment.initContainers.dependencies }}
              echo "Waiting for {{ .name }} ({{ .host }}:{{ .port }})..."
              until nc -z -v -w30 {{ .host }} {{ .port }}; do
                echo "{{ .name }} not ready, retrying in 5s..."
                sleep 5
              done
              {{- end }}

              VAULT_HOST="gradiant-vault"
              VAULT_PORT="8200"
              until wget -q -O - http://$VAULT_HOST:$VAULT_PORT/v1/sys/health?standbyok=true | grep -q '"sealed":false'; do
                echo "Vault is accessible but SEALED. Waiting for manual unsealing..."
                sleep 5
              done
              echo "All dependencies are ready. Continuing startup..."
      containers:
        - name: {{ .Release.Name }}-identityhub
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .port }}
            {{- end }}
          env:
            - name: EDC_VAULT_HASHICORP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gradiant-vault-secret # Ensure this matches your setup job output!
                  key: root_token
                  optional: false
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-identityhub-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          startupProbe:
            httpGet:
              path: /api/observability/check/health
              port: 8182
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/observability/check/health
              port: 8182
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
